services:
  postgres:
    image: 'pgvector/pgvector:pg18'
    environment:
      - 'POSTGRES_DB=extfilter'
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432:5432'
